version: '2'
checks:
  method-complexity:
    config:
      threshold: 10
plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      ignore_warnings: true
exclude_patterns:
  - '**/node_modules/'
  - '**/spec/'
  - '**/*.test.js'
  - '**/broken-files/'
  - '**/*.d.ts'
  - '**/docs/'
  - '**/jsdoc-theme/'
  - '**/demo/'
  - '**/config/'
  - '**/bin/'
