env:
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json
extends:
  - standard
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
rules:
  array-bracket-spacing:
    - error
    - always
  arrow-parens:
    - error
  no-console:
    - error
  brace-style:
    - error
    - 1tbs
    -
      allowSingleLine: false
  curly:
    - error
    - all
  max-len:
    - error
    -
      ignoreComments: true
      ignoreRegExpLiterals: true
      ignoreUrls: true
  no-lonely-if:
    - error
  no-multi-spaces:
    - error
    -
      ignoreEOLComments: true
  no-useless-constructor:
    - off
  '@typescript-eslint/no-useless-constructor':
    - error
  '@typescript-eslint/no-inferrable-types':
    - error
    -
      ignoreParameters: true
      ignoreProperties: true
  '@typescript-eslint/member-delimiter-style':
    - error
    -
      multiline:
        delimiter: none
  '@typescript-eslint/prefer-readonly':
    - error
  '@typescript-eslint/explicit-member-accessibility':
    - error
    -
      overrides:
        constructors: no-public
  '@typescript-eslint/no-empty-interface':
    - error
    -
      allowSingleExtends: true
