env:
  es6: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
    - ./**/tsconfig.json
ignorePatterns:
  - dist
extends:
  - '@alex-taxiera/eslint-config-ts'
  - plugin:prettier/recommended
rules:
  import-newlines/enforce: off
  '@typescript-eslint/no-base-to-string':
    - 'error'
    -
      ignoredTypeNames:
        - 'RegExp'
        - 'Error'
