extends: standard
rules: 
  array-bracket-spacing: 
    - error
    - always
  arrow-parens: 
    - error
  brace-style:
    - error
    - 1tbs
    -
      allowSingleLine: false
  curly: 
    - error
    - all
  max-len: 
    - error
    - 
      ignoreComments: true
      ignoreRegExpLiterals: true
      ignoreUrls: true
  no-lonely-if: 
    - error
  no-multi-spaces: 
    - error
    - 
      ignoreEOLComments: true
